import type { AdminAccountSummary, AdminBatchAction, HostedAPI } from '../../api';
import type { HostedView } from '../../shell';
import { createAccountSelection } from './selection';
import { emptyAccountFilters } from './model';
import { mountAccountDetail } from './detail';
import { mountAdminNotice } from '../ui/notice';
import { runAdminAction } from '../ui/async-action';

export function mountAccountList(host:HTMLElement,api:Pick<HostedAPI,'adminAccounts'|'adminBatch'|'adminAccount'|'updateAdminRoom'|'adjustQuota'|'disableAccount'|'enableAccount'|'issueOBSCredential'>):HostedView{
 const document=host.ownerDocument;const selection=createAccountSelection();const filters=emptyAccountFilters();let rows:AdminAccountSummary[]=[];let cursor:string|undefined;let disposed=false;let generation=0;let detailView:HostedView|undefined;let timer:ReturnType<typeof setTimeout>|undefined;
 const controls=document.createElement('div');controls.className='hosted-admin-account-controls';const search=document.createElement('input');search.placeholder='搜索账号 ID 或直播间';const status=document.createElement('select');status.setAttribute('aria-label','账号状态');for(const [label,value] of [['全部状态',''],['正常','active'],['已停用','disabled']] as const){const option=document.createElement('option');option.value=value;option.textContent=label;status.append(option)}const statusField=document.createElement('label');statusField.className='hosted-admin-field';const statusLabel=document.createElement('span');statusLabel.textContent='账号状态';statusField.append(statusLabel,status);const attention=document.createElement('select');attention.setAttribute('aria-label','关注事项');for(const [label,value] of [['全部账号',''],['缺少直播间','missing_room'],['缺少 OBS','missing_obs']] as const){const option=document.createElement('option');option.value=value;option.textContent=label;attention.append(option)}const attentionField=document.createElement('label');attentionField.className='hosted-admin-field';const attentionLabel=document.createElement('span');attentionLabel.textContent='关注事项';attentionField.append(attentionLabel,attention);controls.append(search,statusField,attentionField);const feedback=document.createElement('div');feedback.className='hosted-admin-feedback';const notice=mountAdminNotice(feedback);const toolbar=document.createElement('div');toolbar.className='hosted-admin-bulk-toolbar';const table=document.createElement('div');table.className='hosted-admin-account-table';const detail=document.createElement('aside');host.append(controls,feedback,toolbar,table,detail);
 const load=async(next=false)=>{const current=++generation;try{const page=await api.adminAccounts({query:filters.query||undefined,status:filters.status||undefined,attention:filters.attention||undefined,cursor:next?cursor:undefined,limit:50});if(disposed||current!==generation)return;rows=next?[...rows,...page.items]:page.items;cursor=page.nextCursor;render()}catch{if(!disposed&&current===generation)table.textContent='账号列表加载失败，请重试'}};
 const submitBatch=(button:HTMLButtonElement,label:string,ids:number[],action:AdminBatchAction,reason:string,quota:number|undefined)=>{let results:Awaited<ReturnType<typeof api.adminBatch>>=[];void runAdminAction(button,{idle:label,busy:`${label}中…`},async()=>{results=await api.adminBatch(ids,action,reason,quota)}).then((outcome)=>{if(outcome==='failure'){notice.show('error','批量操作失败，请重试',()=>submitBatch(button,label,ids,action,reason,quota));return}const failed=results.filter((item)=>item.status==='failed').length;for(const result of results){if(result.status==='succeeded')selection.toggle(result.accountId,false)}notice.show(failed?'warning':'success',failed?`${results.length-failed} 个成功，${failed} 个失败`:`${results.length} 个账号操作成功`);render();void load()})};
 const batch=(button:HTMLButtonElement,label:string,action:AdminBatchAction)=>{const ids=selection.values();if(!ids.length)return;const reason=globalThis.prompt('请输入操作原因')?.trim();if(!reason)return;const quota=action==='set_invitation_quota'?Number(globalThis.prompt('请输入剩余额度')):undefined;submitBatch(button,label,ids,action,reason,quota)};
 const render=()=>{table.replaceChildren();toolbar.replaceChildren();if(selection.size()){const count=document.createElement('span');count.textContent=`已选择 ${selection.size()} 个账号`;toolbar.append(count);for(const [label,action] of [['启用','enable'],['停用','disable'],['调整邀请额度','set_invitation_quota']] as const){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>batch(b,label,action));toolbar.append(b)}const clear=document.createElement('button');clear.type='button';clear.textContent='清除选择';clear.addEventListener('click',()=>{selection.clear();render()});toolbar.append(clear)}const header=document.createElement('div');header.className='hosted-admin-account-row hosted-admin-account-head';const all=document.createElement('input');all.type='checkbox';all.setAttribute('aria-label','全选当前页');all.checked=rows.length>0&&rows.every((row)=>selection.has(row.id));all.addEventListener('change',()=>{selection.togglePage(rows.map((row)=>row.id));render()});header.append(all);for(const label of ['账号','直播间','邀请额度','OBS','操作']){const span=document.createElement('span');span.textContent=label;header.append(span)}table.append(header);for(const row of rows){const line=document.createElement('div');line.className='hosted-admin-account-row';const check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',`选择主播账号 #${row.id}`);check.checked=selection.has(row.id);check.addEventListener('change',()=>{selection.toggle(row.id,check.checked);render()});const account=document.createElement('strong');account.textContent=`主播账号 #${row.id}`;const room=document.createElement('span');room.textContent=row.roomId??'尚未设置';const quota=document.createElement('span');quota.textContent=String(row.invitationQuota);const obs=document.createElement('span');obs.textContent=row.hasObs?'已创建':'未创建';const open=document.createElement('button');open.type='button';open.textContent='详情';open.addEventListener('click',()=>{void detailView?.dispose();detailView=mountAccountDetail(detail,api,row.id,()=>void load())});line.append(check,account,room,quota,obs,open);table.append(line)}if(cursor){const more=document.createElement('button');more.type='button';more.textContent='加载更多';more.addEventListener('click',()=>void load(true));table.append(more)}};
 search.addEventListener('input',()=>{filters.query=search.value;if(timer)clearTimeout(timer);timer=setTimeout(()=>void load(),300)});status.addEventListener('change',()=>{filters.status=status.value as typeof filters.status;void load()});attention.addEventListener('change',()=>{filters.attention=attention.value as typeof filters.attention;void load()});void load();return{async dispose(){disposed=true;generation++;if(timer)clearTimeout(timer);notice.dispose();await detailView?.dispose()}};
}
