/var/log/nginx/gift-panel-update-api.access.log /var/log/nginx/gift-panel-update-api.error.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    create 0640 root adm
    sharedscripts
    postrotate
        /usr/bin/systemctl kill -s USR1 nginx.service
    endscript
}
