/var/log/nginx/gift-panel-hosted.access.log /var/log/nginx/gift-panel-hosted.error.log {
    daily
    rotate 35
    missingok
    compress
    delaycompress
    dateext
    dateformat -%Y%m%d
    sharedscripts
    create 0640 www-data adm
    postrotate
        if [ -s /run/nginx.pid ]; then
            kill -USR1 "$(cat /run/nginx.pid)"
        fi
    endscript
}

/var/log/gift-panel-hosted/app.log {
    daily
    rotate 35
    missingok
    compress
    delaycompress
    dateext
    dateformat -%Y%m%d
    copytruncate
}
