import type { HostedAPI, AdminOverview } from '../api';
import type { HostedView } from '../shell';
import { createAdminState } from './ui/state';

export function mountAdminOverview(host: HTMLElement, api: Pick<HostedAPI,'adminOverview'>, navigate: (section: 'accounts'|'invitations'|'bili-service')=>void): HostedView {
  const document=host.ownerDocument;let disposed=false;
  const load=():void=>{if(disposed)return;host.replaceChildren(createAdminState(document,'loading','正在读取运营数据…'));void api.adminOverview().then((value)=>{if(disposed)return;render(value)}).catch(()=>{if(!disposed)host.replaceChildren(createAdminState(document,'error','运营数据暂不可用，请稍后重试',load));});};
  const render=(value:AdminOverview):void=>{const metrics=document.createElement('div');metrics.className='hosted-admin-metrics';for(const [label,count] of [['账号总数',value.totalAccounts],['正常账号',value.activeAccounts],['需关注',value.attention.length]] as const){const card=document.createElement('section');card.className='hosted-admin-metric';const strong=document.createElement('strong');strong.textContent=String(count);const span=document.createElement('span');span.textContent=label;card.append(strong,span);metrics.append(card)}const attention=document.createElement('section');attention.className='hosted-admin-card';const h=document.createElement('h3');h.textContent='优先处理';attention.append(h);for(const item of value.attention){const row=document.createElement('button');row.type='button';row.textContent=`账号 #${item.accountId} · ${item.text}`;row.addEventListener('click',()=>navigate('accounts'));attention.append(row)}if(value.attention.length===0){const empty=document.createElement('p');empty.textContent='当前没有需要处理的事项';attention.append(empty)}const resources=document.createElement('section');resources.className='hosted-admin-resource-row';for(const [label,description,target] of [['主播账号','管理直播间、邀请额度与 OBS','accounts'],['邀请码','创建、分享与作废邀请码','invitations'],['B站服务账号','检查状态或更换服务账号','bili-service']] as const){const button=document.createElement('button');button.type='button';button.className='hosted-admin-resource-card';const title=document.createElement('strong');title.textContent=label;const detail=document.createElement('span');detail.textContent=description;const arrow=document.createElement('span');arrow.textContent='→';arrow.setAttribute('aria-hidden','true');button.append(title,detail,arrow);button.addEventListener('click',()=>navigate(target));resources.append(button)}const events=document.createElement('section');events.className='hosted-admin-card';const eh=document.createElement('h3');eh.textContent='最近活动';events.append(eh);for(const event of value.recentEvents){const row=document.createElement('p');row.textContent=`${event.accountId?`账号 #${event.accountId} · `:''}${event.text}`;events.append(row)}if(value.recentEvents.length===0){const empty=document.createElement('p');empty.textContent='暂无最近活动';events.append(empty)}const bottom=document.createElement('div');bottom.className='hosted-admin-overview-bottom';bottom.append(attention,events);host.replaceChildren(metrics,resources,bottom)};
  load();return {dispose(){disposed=true}};
}
